# .github/workflows/docker-build.yml
name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Use a specific version like v4.2.2 if needed

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3 # Use a specific version like v3.10.0 if needed

      - name: Docker Login
        uses: docker/login-action@v3 # Use a specific version like v3.4.0 if needed
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6 # Use a specific version like v6.15.0 if needed
        with:
          context: . # Use the root directory as context
          file: ./Dockerfile # Specify the Dockerfile location
          push: true
          tags: shivamb25/unsloth-dev:latest # Use the desired tag format